### ISSUE TITLE
配置好了，执行 python3 main.py 错误。

### ISSUE THREAD

**Issue by ericvlog** [Adachi-Git/qBittorrent2PikPak#1]
(qBittorrent2PikPak) plsharevme@debian:~/appdata/qBittorrent2PikPak$ python3 main.py
Traceback (most recent call last):
  File "/home/plsharevme/appdata/qBittorrent2PikPak/main.py", line 14, in <module>
    main()
  File "/home/plsharevme/appdata/qBittorrent2PikPak/main.py", line 8, in main
    login_and_get_torrent_list("config.json")
  File "/home/plsharevme/appdata/qBittorrent2PikPak/get_torrent_list.py", line 61, in login_and_get_torrent_list
    session_id = login_qbittorrent(username, password, qb_url)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/plsharevme/appdata/qBittorrent2PikPak/get_torrent_list.py", line 14, in login_qbittorrent
    return response.cookies['SID']
           ~~~~~~~~~~~~~~~~^^^^^^^
  File "/home/plsharevme/appdata/qBittorrent2PikPak/lib/python3.11/site-packages/requests/cookies.py", line 334, in __getitem__
    return self._find_no_duplicates(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/plsharevme/appdata/qBittorrent2PikPak/lib/python3.11/site-packages/requests/cookies.py", line 413, in _find_no_duplicates
    raise KeyError(f"name={name!r}, domain={domain!r}, path={path!r}")
KeyError: "name='SID', domain=None, path=None"

不知哪里出错，我没有配置 get_torrent_list.py ,只是配置 config.json 和 qbittorrent。
当安装在 debian 时环境变量好像有问题，
我是根据以下来安装

```
Apologies for the confusion. Let's try this again with the correct username:

Create the virtual environment with the correct permissions:

Copy
sudo -u plsharevme python3 -m venv /home/plsharevme/appdata/qBittorrent2PikPak
This will create the virtual environment with the correct ownership and permissions for the plsharevme user.
Activate the virtual environment:

Copy
source /home/plsharevme/appdata/qBittorrent2PikPak/bin/activate
Install the required packages:
basic

Copy
pip install -r requirements.txt
This should now install the packages without any permission issues.
```

**Comment by Adachi-Git** [comment]
更新了，试一下，一直用的免验证忽视了。

44390bb67b6b70a3d14ccc4a22a17f7a9377ebc0

**Comment by ericvlog** [comment]
> 更新了，试一下，一直用的免验证忽视了。
> 
> [44390bb](https://github.com/Adachi-Git/qBittorrent2PikPak/commit/44390bb67b6b70a3d14ccc4a22a17f7a9377ebc0)

比之前好了看到了 

Downloading torrents saved to hash.json.
ERROR:root:All connection attempts failed
ERROR:root:All connection attempts failed
ERROR:root:All connection attempts failed
Traceback (most recent call last):
  File "C:\Users\plsharevme\qBittorrent2PikPak\main.py", line 14, in <module>
    main()
  File "C:\Users\plsharevme\qBittorrent2PikPak\main.py", line 11, in main
    asyncio.run(download_from_config())
  File "C:\Users\plsharevme\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\plsharevme\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\plsharevme\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\plsharevme\qBittorrent2PikPak\add_torrent.py", line 23, in download_from_config
    await client.login()
  File "C:\Users\plsharevme\AppData\Local\Programs\Python\Python311\Lib\site-packages\pikpakapi\__init__.py", line 257, in login
    user_info = await self._request_post(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\plsharevme\AppData\Local\Programs\Python\Python311\Lib\site-packages\pikpakapi\__init__.py", line 188, in _request_post
    return await self._make_request("post", url, data=data, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\plsharevme\AppData\Local\Programs\Python\Python311\Lib\site-packages\pikpakapi\__init__.py", line 173, in _make_request
    raise PikpakException(error_decription)
pikpakapi.PikpakException.PikpakException

**Comment by Adachi-Git** [comment]
> > 更新了，试一下，一直用的免验证忽视了。
> > [44390bb](https://github.com/Adachi-Git/qBittorrent2PikPak/commit/44390bb67b6b70a3d14ccc4a22a17f7a9377ebc0)
> 
> 比之前好了看到了
> 
> Downloading torrents saved to hash.json. ERROR:root:All connection attempts failed ERROR:root:All connection attempts failed ERROR:root:All connection attempts failed Traceback (most recent call last): File "C:\Users\plsharevme\qBittorrent2PikPak\main.py", line 14, in main() File "C:\Users\plsharevme\qBittorrent2PikPak\main.py", line 11, in main asyncio.run(download_from_config()) File "C:\Users\plsharevme\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run return runner.run(main) ^^^^^^^^^^^^^^^^ File "C:\Users\plsharevme\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run return self._loop.run_until_complete(task) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\plsharevme\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete return future.result() ^^^^^^^^^^^^^^^ File "C:\Users\plsharevme\qBittorrent2PikPak\add_torrent.py", line 23, in download_from_config await client.login() File "C:\Users\plsharevme\AppData\Local\Programs\Python\Python311\Lib\site-packages\pikpakapi__init__.py", line 257, in login user_info = await self._request_post( ^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\plsharevme\AppData\Local\Programs\Python\Python311\Lib\site-packages\pikpakapi__init__.py", line 188, in _request_post return await self._make_request("post", url, data=data, headers=headers) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\plsharevme\AppData\Local\Programs\Python\Python311\Lib\site-packages\pikpakapi__init__.py", line 173, in _make_request raise PikpakException(error_decription) pikpakapi.PikpakException.PikpakException

pip install -r requirements.txt
确保账号密码无误，登录 pikpak 需要使用代理，在 config 里自行配置。

**Comment by ericvlog** [comment]
我在马来西亚，已经人肉翻墙了，登入应该不用代理啊。。。。

**Comment by Adachi-Git** [comment]
> 我在马来西亚，已经人肉翻墙了，登入应该不用代理啊。。。。
> 
db27fbab2309aedee29d4d9ff790796f82e32281
更新一下。
也更新下依赖 pip install -r requirements.txt
检查 config 文件有没有问题，实在不行直接挂代理试试。
明天下班再看。

**Comment by ericvlog** [comment]
> > 我在马来西亚，已经人肉翻墙了，登入应该不用代理啊。。。。
> 
> 更新一下。 也更新下依赖 pip install -r requirements.txt 检查 config 文件有没有问题，实在不行直接挂代理试试。
> 
> 明天下班再看。

那个代理可以移除吗？"proxy": "http://127.0.0.1:30001" 
还是不能，没关系你早点休息。

**Comment by ericvlog** [comment]
"proxy": "" 完全移除代理可以了。

Downloading from magnet link: magnet:?xt=urn:btih:86f27fb41a70c9210d4788b80f3569fbc72dfec2
Download result: {'upload_type': 'UPLOAD_TYPE_URL', 'url': {'kind': 'upload#url'}, 'file': None, 'task': {'kind': 'drive#task', 'id': 'VO3me1Zqi36kRD4x_c8vlMO4o1', 'name': '情劫1993.国粤中字.MFL.mkv', 'type': 'offline', 'user_id': 'Zn5wf2TEUoK-9WDg', 'statuses': [], 'status_size': 1, 'params': {'predict_speed': '73300775185', 'predict_type': '3'}, 'file_id': 'VO3me1bki36kRD4x_c8vlMOMo1', 'file_name': '情劫1993.国粤中字.MFL.mkv', 'file_size': '960865771', 'message': 'Saving', 'created_time': '2024-08-08T23:42:47.094+08:00', 'updated_time': '2024-08-08T23:42:47.094+08:00', 'third_task_id': '', 'phase': 'PHASE_TYPE_RUNNING', 'progress': 0, 'icon_link': '', 'callback': '', 'reference_resource': None, 'space': ''}}
==============================

谢谢 大哥

**Comment by Adachi-Git** [comment]
> ```
> "proxy": "" 完全移除代理可以了。
> ```
笑，这里是我自己的代理，反而误导用户了。
有问题再反馈。
